apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: yoyota/upload-to-minio
deploy:
  helm:
    releases:
      - name: upload-to-minio
        namespace: yoyota
        chartPath: helm
        setValueTemplates:
          image.repository: "{{.IMAGE_NAME}}"
          image.tag: "{{.DIGEST_HEX}}"
